addons:
  apt:
    packages:
      - python-dateutil

# Verify that the JSON is correct (including the dates)
script:
  - python check-tokens-format.py

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
