addons:
  apt:
    packages:
      - jq

# Verify that the JSON is correct
script:
  - cat tokens.json | ./jq -e . >/dev/null 2>&1

# Deploy to GitHub pages
deploy:
  provider: pages
  edge:
    branch: v1.8.47
  skip_cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  on:
    branch: master
